# Generated by Django 5.0.7 on 2025-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureregistration',
            name='student_name',
            field=models.CharField(blank=True, help_text='Name of the student registering for the lecture', max_length=100, null=True),
        ),
    ]
