# Generated by Django 5.0.7 on 2025-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_response',
            field=models.TextField(blank=True, help_text="Doctor's response or notes about the appointment", null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
