# Generated by Django 5.0.7 on 2025-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_options_appointment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Name of the patient for the appointment', max_length=100, null=True),
        ),
    ]
